# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_model.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12server_model.proto\x12\x0cserver_model\"Y\n\x12\x42\x61tchPredictionIns\x12\x12\n\nembeddings\x18\x01 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x02 \x01(\x0e\x32\x19.server_model.ControlCode\"Z\n\x12\x42\x61tchPredictionRes\x12\x13\n\x0bpredictions\x18\x01 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x02 \x01(\x0e\x32\x19.server_model.ControlCode\"r\n\x1bGradientDescentDataBatchIns\x12\x12\n\nembeddings\x18\x01 \x01(\x0c\x12\x0e\n\x06labels\x18\x02 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x03 \x01(\x0e\x32\x19.server_model.ControlCode\"`\n\x1bGradientDescentDataBatchRes\x12\x10\n\x08gradient\x18\x01 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x02 \x01(\x0e\x32\x19.server_model.ControlCode\"W\n\x14UpdateServerModelRes\x12/\n\x0c\x63ontrol_code\x18\x01 \x01(\x0e\x32\x19.server_model.ControlCode\x12\x0e\n\x06result\x18\x02 \x01(\x0c\"W\n\x10\x44\x61taBatchForward\x12\x12\n\nembeddings\x18\x01 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x02 \x01(\x0e\x32\x19.server_model.ControlCode\"V\n\x11\x44\x61taBatchBackward\x12\x10\n\x08gradient\x18\x01 \x01(\x0c\x12/\n\x0c\x63ontrol_code\x18\x02 \x01(\x0e\x32\x19.server_model.ControlCode*]\n\x0b\x43ontrolCode\x12\x06\n\x02OK\x10\x00\x12\x13\n\x0f\x44O_CLOSE_STREAM\x10\x01\x12\x14\n\x10STREAM_CLOSED_OK\x10\x02\x12\x1b\n\x17\x45RROR_PROCESSING_STREAM\x10\x03\x32\xf2\x03\n\x0bServerModel\x12^\n\x16ServePredictionRequest\x12 .server_model.BatchPredictionIns\x1a .server_model.BatchPredictionRes\"\x00\x12t\n\x1aServeGradientUpdateRequest\x12).server_model.GradientDescentDataBatchIns\x1a).server_model.GradientDescentDataBatchRes\"\x00\x12n\n\x19UpdateServerModelRequests\x12).server_model.GradientDescentDataBatchIns\x1a\".server_model.UpdateServerModelRes\"\x00(\x01\x12L\n\x08UForward\x12\x1e.server_model.DataBatchForward\x1a\x1e.server_model.DataBatchForward\"\x00\x12O\n\tUBackward\x12\x1f.server_model.DataBatchBackward\x1a\x1f.server_model.DataBatchBackward\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTROLCODE']._serialized_start=699
  _globals['_CONTROLCODE']._serialized_end=792
  _globals['_BATCHPREDICTIONINS']._serialized_start=36
  _globals['_BATCHPREDICTIONINS']._serialized_end=125
  _globals['_BATCHPREDICTIONRES']._serialized_start=127
  _globals['_BATCHPREDICTIONRES']._serialized_end=217
  _globals['_GRADIENTDESCENTDATABATCHINS']._serialized_start=219
  _globals['_GRADIENTDESCENTDATABATCHINS']._serialized_end=333
  _globals['_GRADIENTDESCENTDATABATCHRES']._serialized_start=335
  _globals['_GRADIENTDESCENTDATABATCHRES']._serialized_end=431
  _globals['_UPDATESERVERMODELRES']._serialized_start=433
  _globals['_UPDATESERVERMODELRES']._serialized_end=520
  _globals['_DATABATCHFORWARD']._serialized_start=522
  _globals['_DATABATCHFORWARD']._serialized_end=609
  _globals['_DATABATCHBACKWARD']._serialized_start=611
  _globals['_DATABATCHBACKWARD']._serialized_end=697
  _globals['_SERVERMODEL']._serialized_start=795
  _globals['_SERVERMODEL']._serialized_end=1293
# @@protoc_insertion_point(module_scope)
