# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import slower.proto.server_model_pb2 as server__model__pb2


class ServerModelStub(object):
    """compile with the following command:
    python -m grpc_tools.protoc -I=proto/ --python_out=slower/proto/ --pyi_out=slower/proto/ --grpc_python_out=slower/proto/ proto/server_model.proto
    also update `slower.proto.server_model_pb2` in `server_model_pb2_grpc.py`

    The server model service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BlockingRequest = channel.unary_unary(
                '/server_model.ServerModel/BlockingRequest',
                request_serializer=server__model__pb2.BatchData.SerializeToString,
                response_deserializer=server__model__pb2.BatchData.FromString,
                )
        self.StreamingRequests = channel.stream_unary(
                '/server_model.ServerModel/StreamingRequests',
                request_serializer=server__model__pb2.BatchData.SerializeToString,
                response_deserializer=server__model__pb2.BatchData.FromString,
                )


class ServerModelServicer(object):
    """compile with the following command:
    python -m grpc_tools.protoc -I=proto/ --python_out=slower/proto/ --pyi_out=slower/proto/ --grpc_python_out=slower/proto/ proto/server_model.proto
    also update `slower.proto.server_model_pb2` in `server_model_pb2_grpc.py`

    The server model service definition.
    """

    def BlockingRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRequests(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BlockingRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockingRequest,
                    request_deserializer=server__model__pb2.BatchData.FromString,
                    response_serializer=server__model__pb2.BatchData.SerializeToString,
            ),
            'StreamingRequests': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamingRequests,
                    request_deserializer=server__model__pb2.BatchData.FromString,
                    response_serializer=server__model__pb2.BatchData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_model.ServerModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerModel(object):
    """compile with the following command:
    python -m grpc_tools.protoc -I=proto/ --python_out=slower/proto/ --pyi_out=slower/proto/ --grpc_python_out=slower/proto/ proto/server_model.proto
    also update `slower.proto.server_model_pb2` in `server_model_pb2_grpc.py`

    The server model service definition.
    """

    @staticmethod
    def BlockingRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_model.ServerModel/BlockingRequest',
            server__model__pb2.BatchData.SerializeToString,
            server__model__pb2.BatchData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingRequests(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/server_model.ServerModel/StreamingRequests',
            server__model__pb2.BatchData.SerializeToString,
            server__model__pb2.BatchData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
