# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import slower.proto.server_segment_pb2 as server__segment__pb2


class ServerSegmentStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServePredictionRequest = channel.unary_unary(
                '/server_segment.ServerSegment/ServePredictionRequest',
                request_serializer=server__segment__pb2.BatchPredictionIns.SerializeToString,
                response_deserializer=server__segment__pb2.BatchPredictionRes.FromString,
                )
        self.ServeGradientUpdateRequest = channel.unary_unary(
                '/server_segment.ServerSegment/ServeGradientUpdateRequest',
                request_serializer=server__segment__pb2.GradientDescentDataBatchIns.SerializeToString,
                response_deserializer=server__segment__pb2.GradientDescentDataBatchRes.FromString,
                )


class ServerSegmentServicer(object):
    """The greeting service definition.
    """

    def ServePredictionRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeGradientUpdateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerSegmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServePredictionRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ServePredictionRequest,
                    request_deserializer=server__segment__pb2.BatchPredictionIns.FromString,
                    response_serializer=server__segment__pb2.BatchPredictionRes.SerializeToString,
            ),
            'ServeGradientUpdateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeGradientUpdateRequest,
                    request_deserializer=server__segment__pb2.GradientDescentDataBatchIns.FromString,
                    response_serializer=server__segment__pb2.GradientDescentDataBatchRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_segment.ServerSegment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerSegment(object):
    """The greeting service definition.
    """

    @staticmethod
    def ServePredictionRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_segment.ServerSegment/ServePredictionRequest',
            server__segment__pb2.BatchPredictionIns.SerializeToString,
            server__segment__pb2.BatchPredictionRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeGradientUpdateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server_segment.ServerSegment/ServeGradientUpdateRequest',
            server__segment__pb2.GradientDescentDataBatchIns.SerializeToString,
            server__segment__pb2.GradientDescentDataBatchRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
